name:                rss-dummy-backend
version:             0.1.0.0
github:              "tvestelind/rss-dummy-backend"
license:             BSD3
author:              "Tomas Vestelind"
maintainer:          "tomas.vestelind@gmail.com"
copyright:           "none"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            hobby-project

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/tvestelind/rss-dummy-backend#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
    - aeson
    - containers
    - directory
    - feed
    - filepath
    - http-types
    - lens
    - optparse-applicative
    - servant-server
    - servant-swagger
    - servant-swagger-ui
    - swagger2
    - text
    - uuid
    - wai
    - wai-cors
    - warp

executables:
  rss-dummy-backend-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - rss-dummy-backend

tests:
  rss-dummy-backend-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - rss-dummy-backend
